
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 27 01:06:16 BRT 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class SymbolCodes {
  /* terminals */
  public static final int KWPRINT = 21;
  public static final int ABRE_CHAVE = 8;
  public static final int KWIF = 17;
  public static final int FECHA_CHAVE = 7;
  public static final int OP_MAIORIGUAL = 26;
  public static final int OP_VIRGULA = 11;
  public static final int OP_MENORIGUAL = 28;
  public static final int OP_DIV = 34;
  public static final int IDENTIFICADOR = 6;
  public static final int OP_DIFERENTE = 24;
  public static final int OP_MOD = 35;
  public static final int KWCLASS = 4;
  public static final int ABRE_COLCHETE = 15;
  public static final int EOF = 0;
  public static final int ABRE_PARENTESES = 13;
  public static final int KWVOID = 5;
  public static final int error = 1;
  public static final int OP_MULT = 33;
  public static final int KWRETURN = 19;
  public static final int OP_PONTOEVIRGULA = 10;
  public static final int KWELSE = 22;
  public static final int KWREAD = 20;
  public static final int OP_PONTO = 31;
  public static final int FECHA_COLCHETE = 16;
  public static final int OP_IGUAL = 23;
  public static final int KWNEW = 30;
  public static final int INTEIRO = 36;
  public static final int KWPROGRAMA = 2;
  public static final int CHARCONST = 12;
  public static final int FECHA_PARENTESES = 14;
  public static final int FLOAT = 37;
  public static final int OP_RECEBE = 9;
  public static final int KWFINAL = 3;
  public static final int OP_MAIS = 32;
  public static final int KWWHILE = 18;
  public static final int OP_MAIOR = 25;
  public static final int OP_MENOS = 29;
  public static final int OP_MENOR = 27;
}

